name: Build and Deploy to Az Web app

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./application/SampleWeb

env:
  AZURE_WEBAPP_NAME: codewebapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'          # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo and login
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
          echo ========================================
          ls '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
          (cd myapp && zip -r ../package.zip .)
          echo ========================================
          ls ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      - name: check
        run: |
          echo ========================================
          pwd
          echo ========================================
          ls '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          echo ========================================
          ls '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
  
      - uses: Azure/cli@v1
        name: aswelk deploy
        with:
          inlineScript: |
            pwd
            ls
            echo ========================================
            ls ./application/SampleWeb
            az account list
#            az webapp deploy --resource-group ${{ secrets.AZURE_RG }} --name ${{ env.AZURE_WEBAPP_NAME }} --src-path package.zip
    
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: './application/SampleWeb/myapp'
      
      - name: logout
        run: |
          az logout
